language: node_js
node_js:
  - '7'
script:
  - echo 'Deploy!!'
install:
 - npm install -g firebase-tools yarn
 - yarn install
script:
 - yarn build
after_success:
 - firebase deploy --only hosting:webunconfid --project pwaid-dir --token $FIREBASE_TOKEN