language: node_js
branches:
  only:
  - master
node_js:
  - '8'
script:
  - echo 'Deploy!!'
install:
  - npm install -g firebase-tools yarn
  - yarn install
script:
  - yarn build
after_success:
  - firebase deploy --only hosting:webunconfid --token $FIREBASE_TOKEN