language: node_js
branches:
  only:
    - master
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules

script:
  - echo 'Deploy!!'
before_install:
  - npm install -g firebase-tools yarn
install:
  - yarn install
script:
  - yarn build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN